# Generated by Django 6.0.4 on 2026-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='Ex: Abidjan, Luxembourg, Remote', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('website', models.URLField(blank=True)),
                ('job_title', models.CharField(help_text='Ex: Administrateur de Bases de Données', max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Laissez vide si vous y êtes encore', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Décrivez vos missions principales (ex: Migration Oracle 11g vers PostgreSQL)')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status_label', models.CharField(default='OPERATIONAL', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('index_number', models.CharField(help_text='Ex: 01, 02', max_length=10)),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('tech_stack', models.CharField(help_text='Liste séparée par des virgules', max_length=250)),
                ('github_link', models.URLField(blank=True)),
                ('live_link', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('mobile', 'Mobile'), ('devops', 'DevOps'), ('infra', 'Infra')], max_length=20)),
                ('icon_name', models.CharField(help_text="Nom de l'icône Material Symbols", max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
