# Generated by Django 6.0.4 on 2026-09-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_nyc_taxi_merge_pbix_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(help_text='Ex: Amazon Web Services (AWS)', max_length=150)),
                ('issue_date', models.DateField()),
                ('icon_name', models.CharField(default='workspace_premium', help_text="Nom de l'icône Material Symbols", max_length=50)),
                ('certificate_file', models.FileField(blank=True, help_text='Certificat au format PDF (optionnel)', null=True, upload_to='certifications/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', '-issue_date'],
            },
        ),
    ]
