# Generated by Django 6.0.4 on 2026-10-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_maintenance_image_and_nyc_taxi_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('data', 'Data & IA'), ('dev', 'Développement')], default='data', max_length=10),
        ),
    ]
