# Generated by Django 6.0.4 on 2026-10-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_iuc_description_288_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='download_label_alt',
            field=models.CharField(blank=True, help_text='Ex: .zip portable', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='download_link_alt',
            field=models.URLField(blank=True, help_text='Second lien de téléchargement (ex: version portable)'),
        ),
    ]
