# Generated by Django 6.0.4 on 2026-10-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_iuc_text_and_portable'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.URLField(blank=True, help_text='Vidéo de présentation (mp4), ouverte en plein écran depuis le titre'),
        ),
    ]
