# Generated by Django 6.0.4 on 2026-10-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_chatbot_rag_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.CharField(blank=True, help_text='Vidéo de présentation (mp4) ouverte en plein écran : URL absolue ou chemin statique (ex: core/videos/x.mp4)', max_length=300),
        ),
    ]
